version: '3.8'

services:
  backend:
    build:
      context: ./DeliveryFolder/backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
    command: ["node", "server.js"]
    depends_on:
      - mongo

  frontend:
    build:
      context: ./DeliveryFolder/frontend
      dockerfile: Dockerfile
      args:
        TARGET: prod # Ensures frontend is built with Nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
