version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    volumes:
      # Mount only the *source code* you want to hot-reload
      - ./backend:/app:delegated
      # Exclude node_modules, let Docker keep the container's own
      # To do that, we can specify a named volume to override node_modules inside container
      - backend_node_modules:/app/node_modules
    command: ["npx", "nodemon", "server.js"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  backend_node_modules:
  frontend_node_modules:
