version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:delegated
      - backend_node_modules:/app/node_modules
    command: ["npx", "nodemon", "server.js"]
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        TARGET: dev # Set default to development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  backend_node_modules:
  frontend_node_modules:
  mongo_data:
