name: Branch Protection Check

on:
  pull_request:
    branches: [main, develop]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Block Draft PRs to Develop
        run: |
          if [[ "${{ github.base_ref }}" == "develop" && "${{ github.event.pull_request.draft }}" == "true" ]]; then
            echo "❌ Draft PRs cannot be merged to develop"
            exit 1
          fi
