name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - feature/prototype-v1-testing  # Change if deploying from another branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install --no-package-lock
        working-directory: frontend  # Ensure commands run in frontend folder

      - name: Build Project
        run: npm run build
        working-directory: frontend

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: frontend/dist  # Upload the built files from frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
